name: Lightpanda Browser ARM64 Build

on:
    schedule:
        - cron: "0 3 * * *" # Run at 3 AM UTC every day
    workflow_dispatch: # Allow manual trigger

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get commit hash
              id: commit
              run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PAT }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./arm64.Dockerfile
                  push: true
                  platforms: linux/arm64
                  tags: |
                      andalouse/lightpanda-browser:nightly-arm64
                      andalouse/lightpanda-browser:${{ steps.commit.outputs.COMMIT_HASH }}-arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
